spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: TuMail
    password: ContraseñaDeTuMail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: CLIMALERT2.0


rest-weather:
  base-url: https://api.weatherapi.com/v1
  q : Buenos Aires
  key: TuKey